import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#c2652a",
        "on-surface-variant": "#605850",
        "on-error": "#ffffff",
        "surface-tint": "#c2652a",
        "on-tertiary-fixed": "#2e1515",
        "on-secondary-fixed-variant": "#504840",
        "surface": "#faf5ee",
        "tertiary-fixed": "#fce0e0",
        "on-error-container": "#7a1a10",
        "on-secondary-container": "#605850",
        "on-secondary": "#ffffff",
        "secondary-container": "#eae2da",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#e8a0a0",
        "outline": "#9a9088",
        "inverse-on-surface": "#faf5ee",
        "surface-dim": "#dcd6cc",
        "surface-container-low": "#f6f0e8",
        "surface-container-highest": "#e6e0d6",
        "surface-container-high": "#ece6dc",
        "on-background": "#3a302a",
        "error": "#c0392b",
        "on-primary-fixed-variant": "#8a4518",
        "secondary-fixed-dim": "#cec6be",
        "surface-container-lowest": "#ffffff",
        "background": "#faf5ee",
        "outline-variant": "#d8d0c8",
        "primary-fixed-dim": "#f0a878",
        "primary-container": "#e08850",
        "secondary-fixed": "#eae2da",
        "inverse-surface": "#3a302a",
        "secondary": "#78706a",
        "on-surface": "#3a302a",
        "on-primary-container": "#fbe8d8",
        "on-tertiary-fixed-variant": "#6e3030",
        "on-primary-fixed": "#401a08",
        "error-container": "#fce4e0",
        "tertiary": "#8c3c3c",
        "primary-fixed": "#fbe8d8",
        "on-tertiary-container": "#3a2020",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#d47070",
        "surface-bright": "#faf5ee",
        "surface-container": "#f2ece4",
        "inverse-primary": "#f0a878",
        "surface-variant": "#ece6dc",
        "on-secondary-fixed": "#2a2420"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "margin-desktop": "48px",
        "sm": "8px",
        "gutter": "24px",
        "2xl": "48px",
        "margin-mobile": "16px",
        "md": "16px",
        "xs": "4px",
        "xl": "32px",
        "lg": "24px",
        "unit": "4px",
        "3xl": "64px"
      },
      fontFamily: {
        "label-sm": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "headline-lg": ["EB Garamond", "serif"],
        "label-md": ["Manrope", "sans-serif"],
        "display-lg": ["EB Garamond", "serif"],
        "headline-md": ["EB Garamond", "serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "headline-lg-mobile": ["EB Garamond", "serif"],
        "title-lg": ["EB Garamond", "serif"]
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
};
export default config;
